POST http://127.0.0.1:5000/user/
Content-Type: application/json

{
  "name": "Natalia",
  "password": "Bednarska",
  "access": "master"
}

###
GET http://127.0.0.1:5000/user/


DELETE http://127.0.0.1:5000/user/5